### PR TITLE
Added dracut module, updated Makefile

### PR DESCRIPTION
**Pull request by rolffokkens**
The dracut module is there now, it's also included in de the Makefile.
While changing the Makefile I also made it more generic; it can now be used by Fedora without patching. But without passing params (SBINDIR=/usr/sbin etc) to the make command it's functionality defaults to what is it was before,

### CODE REVIEW

**Comment by g2p** [comment]
Please split out the Makefile changes that aren't related to Dracut into a later patch which can be reviewed separately.  The PREFIX stuff is inconsistent, it should look like `SBINDIR=$(PREFIX)/sbin` with no references to PREFIX after the declarations.  Also explain why you add -p on every line, it makes the diff less readable and I don't think it does anything for package building.

In the Dracut module, I'd like you to split out a `blkid_does_bcache` function to replace the copy-pasted while loop.

**Comment by g2p** [comment]
Actually, on rereading the Makefile, the lines that don't reference PREFIX all do it on purpose due to hardcoded paths udev needs. I've pushed a small change to make it explicit.

**Comment by rolffokkens** [comment]
After some thought I left out detecting if "blkid does bcache" in the dracut module completely. It's used in two places:
1. checks if "blkid does bcache" OR probe-bcache is present. probe-bcache always so, no need to test it.
2. if "blkid does NOT do bcache" probe-bcache is copied to initramfs. It's better to always copy it.
The dracut module is now much cleaner;

**Comment by rolffokkens** [comment]
The -p option for install is the result of Fedora packaging guidelines:
http://fedoraproject.org/wiki/Packaging:Guidelines#Timestamps

Fedora packages should always install in /usr/bin, /usr/sbin, /usr/lib/dracut etc. and never in /bin, /sbin/ /lib/dracut etc. Having the Makefile handle the Fedora case as well, would be useful for Fedora Packaging.

**Comment by rolffokkens** [comment]
The INSTALL macro would allow me to do "make install INSTALL="install -p", and that's conforming to Fedora Packaging Guidelines.

**Comment by g2p** [comment]
I've cleaned up the history a bit and merged it. I like the Dracut changes. I'm pretty sure the timestamps are entirely pointless (built files, and we don't do tarball releases), but I left the INSTALL thing.

**Pull request closed without merging**
